from pandas import read_csv
from matplotlib.pyplot import figure, xticks, show, savefig
import matplotlib.pyplot as plt
from ts_functions import plot_series, HEIGHT

data = read_csv('../droughtDrop.csv', index_col='date', sep=',', decimal='.', parse_dates=True, dayfirst=True)
print("Nr. Records = ", data.shape[0])
print("First timestamp", data.index[0])
print("Last timestamp", data.index[-1])

day_df = data.copy().groupby(data.index.date).mean()
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(day_df, title='Daily', x_label='timestamp')
plt.gca().legend('QV2M')
xticks(rotation = 45)
show()
savefig("imagesD2Granularity/daily.png")

index = data.index.to_period('W')
week_df = data.copy().groupby(index).mean()
week_df['timestamp'] = index.drop_duplicates().to_timestamp()
week_df.set_index('timestamp', drop=True, inplace=True)
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(week_df, title='Weekly', x_label='timestamp')
plt.gca().legend('QV2M')
xticks(rotation = 45)
show()
savefig("imagesD2Granularity/weekly.png")

index = data.index.to_period('H')
week_df = data.copy().groupby(index).mean()
week_df['timestamp'] = index.drop_duplicates().to_timestamp()
week_df.set_index('timestamp', drop=True, inplace=True)
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(week_df, title='Hourly', x_label='timestamp')
plt.gca().legend('QV2M')
xticks(rotation = 45)
show()
savefig("imagesD2Granularity/hourly.png")


index = data.index.to_period('M')
month_df = data.copy().groupby(index).mean()
month_df['timestamp'] = index.drop_duplicates().to_timestamp()
month_df.set_index('timestamp', drop=True, inplace=True)
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(month_df, title='Monthly', x_label='timestamp')
plt.gca().legend('QV2M')
show()
savefig("imagesD2Granularity/monthly.png")


index = data.index.to_period('Q')
quarter_df = data.copy().groupby(index).mean()
quarter_df['timestamp'] = index.drop_duplicates().to_timestamp()
quarter_df.set_index('timestamp', drop=True, inplace=True)
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(quarter_df, title='Quarterly', x_label='timestamp')
plt.gca().legend('QV2M')
show()
savefig("imagesD2Granularity/quarterly.png")

index = data.index.to_period('Y')
quarter_df = data.copy().groupby(index).mean()
quarter_df['timestamp'] = index.drop_duplicates().to_timestamp()
quarter_df.set_index('timestamp', drop=True, inplace=True)
figure(figsize=(3*HEIGHT, HEIGHT))
plot_series(quarter_df, title='Yearly', x_label='timestamp')
plt.gca().legend('QV2M')
show()
savefig("imagesD2Granularity/yearly.png")